<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API access token' => '',
    'Email' => '',
    'Expire At' => '',
    'Not Active' => 'Não Ativo',
    'Password' => 'Senha',
    'Roles' => '',
    'Token' => '',
    '"{attribute}" must be a valid JSON' => '"{attribute}" debe de ser JSON válido',
    'Active' => 'Ativo',
    'Article ID' => 'ID Artículo',
    'Article View' => 'Vista de Artículo',
    'Author' => 'Autor',
    'Base URL' => 'URL Base',
    'Base Url' => 'Url Base',
    'Body' => 'Corpo',
    'Caption' => 'Subtítulo',
    'Carousel ID' => 'Carrossel ID',
    'Category' => 'Categoria',
    'Comment' => 'Comentário',
    'Component' => 'Componente',
    'Config' => 'Configuração',
    'Created At' => 'Criado em',
    'Created at' => 'Criado em',
    'Deleted' => 'Apagado',
    'Down to maintenance.' => 'Apagado por mantenimiento.',
    'E-mail' => 'E-mail',
    'File Type' => 'Tipo arquivo',
    'Firstname' => 'Nome',
    'Gender' => 'Genero',
    'ID' => 'ID',
    'Image' => 'Imagen',
    'Key' => 'Chave',
    'Last login' => 'Último Login',
    'Lastname' => 'Último Nome',
    'Locale' => 'Localização',
    'Middlename' => 'Segundo Nome',
    'Name' => 'Nome',
    'Order' => 'Orden',
    'Page View' => 'Visualização Página',
    'Parent Category' => 'Categoria Parente',
    'Path' => 'Rota',
    'Picture' => 'Imagen',
    'Published' => 'Publicado',
    'Published At' => 'Publicado por',
    'Size' => 'Tamanho',
    'Slug' => 'Slug',
    'Status' => 'Estado',
    'Thumbnail' => 'Miniatura',
    'Title' => 'Título',
    'Type' => 'Tipo',
    'Updated At' => 'Atualizado em',
    'Updated at' => 'Atualizado em',
    'Updater' => 'Atualizado por',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'Usuário ID',
    'Username' => 'Nome de Usuário',
    'Value' => 'Valor',

    'Gender' => 'Sexo',
    'Date Of Birth' => 'Data de Nascimento',
    'Phone' => 'Telefone',
    'Cell Phone' => 'Celular',
    'City' => 'Cidade',
    'Neighborhood' => 'Bairro',
    'Address' => 'Enderço',
];